user:
  name: "202405134110"
  password: "Quanyusa123"
option:
  driver: msedge
  browser_path: 
  delay_time_s: 10
  enabled_random_time: True
  question_classification: 0

question-urls:
  - https://qah5.zhihuishu.com/qa.html#/web/home/1000006248?role=2&recruitId=321831&VNK=ac33d155
  - 
  - 
  - 

OpenAI:
  base_url: "https://api.suanli.cn/v1"
  api_key: "sk-W0rpStc95T7JVYVwDYc29IyirjtpPPby6SozFMQr17m8KWeo"
  model: "free:QwQ-32B"
  max_tokens: 1000
  temperature: 0.3
